e = open("exp3.txt",'w')
e.write("Hi")
e= open("exp3.txt",'r')
print("Original Text:\n"+e.read()+"\n")
e = open("exp3.txt",'a')
e.write("\nWassup")
e = open("exp3.txt",'r')
print("Appended Text:\n"+e.read()+"\n")
